// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Villa.Data;

#nullable disable

namespace Villa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Villa.Models.VillaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Rate")
                        .HasColumnType("double");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("occupcys")
                        .HasColumnType("int");

                    b.Property<int>("sqft")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            Details = "Thanks",
                            ImageUrl = "sadf",
                            Name = "Kiran",
                            Rate = 3.0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createddate = new DateTime(2025, 11, 13, 10, 46, 53, 425, DateTimeKind.Local).AddTicks(8194),
                            occupcys = 2,
                            sqft = 4
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            Details = "Tdhanks",
                            ImageUrl = "sdadf",
                            Name = "ran",
                            Rate = 33.0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createddate = new DateTime(2025, 11, 13, 10, 46, 53, 425, DateTimeKind.Local).AddTicks(8227),
                            occupcys = 23,
                            sqft = 43
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            Details = "Tfssfhanks",
                            ImageUrl = "sadf3f",
                            Name = "33Kiran",
                            Rate = 35.0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createddate = new DateTime(2025, 11, 13, 10, 46, 53, 425, DateTimeKind.Local).AddTicks(8230),
                            occupcys = 24,
                            sqft = 46
                        },
                        new
                        {
                            Id = 12,
                            Amenity = "",
                            Details = "Trrhanks",
                            ImageUrl = "savcdf",
                            Name = "K3reiran",
                            Rate = 37.0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createddate = new DateTime(2025, 11, 13, 10, 46, 53, 425, DateTimeKind.Local).AddTicks(8233),
                            occupcys = 26,
                            sqft = 48
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
